### ISSUE TITLE
Failure on lein figwheel

### ISSUE THREAD

**Issue by elsehow** [metasoarous/catalysis#11]
hi! on `lein figwheel`, I get

```
clojure.lang.ExceptionInfo: No such namespace: datsync.client.core, could not locate datsync/client/core.cljs, datsync/client/core.cljc, or Closure namespace "datsync.client.core" {:tag :cljs/analysis-error}
    at clojure.core$ex_info.invoke(core.clj:4593)
    at cljs.analyzer$error.invoke(analyzer.cljc:562)
    at cljs.analyzer$error.invoke(analyzer.cljc:560)
    at cljs.analyzer$analyze_deps.invoke(analyzer.cljc:1668)
    at cljs.analyzer$ns_side_effects.invoke(analyzer.cljc:2504)
    at cljs.analyzer$analyze_STAR_$fn__16750.invoke(analyzer.cljc:2585)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:333)
    at clojure.core$reduce.invoke(core.clj:6518)
    at cljs.analyzer$analyze_STAR_.invoke(analyzer.cljc:2585)
    at cljs.analyzer$analyze.invoke(analyzer.cljc:2600)
    at cljs.analyzer$analyze_file$fn__16801.invoke(analyzer.cljc:2844)
    at cljs.analyzer$analyze_file.invoke(analyzer.cljc:2839)
    at figwheel_sidecar.repl$analyze_build.invoke(repl.clj:250)
    at figwheel_sidecar.repl$analyze_builds.invoke(repl.clj:255)
    at figwheel_sidecar.repl$run_autobuilder_helper.invoke(repl.clj:303)
    at figwheel_sidecar.repl$start_autobuild.invoke(repl.clj:374)
    at figwheel_sidecar.repl$run_autobuilder.invoke(repl.clj:546)
    at user$eval22376.invoke(form-init6378408368933993555.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6782)
    at clojure.lang.Compiler.eval(Compiler.java:6772)
    at clojure.lang.Compiler.load(Compiler.java:7227)
    at clojure.lang.Compiler.loadFile(Compiler.java:7165)
    at clojure.main$load_script.invoke(main.clj:275)
    at clojure.main$init_opt.invoke(main.clj:280)
    at clojure.main$initialize.invoke(main.clj:308)
    at clojure.main$null_opt.invoke(main.clj:343)
    at clojure.main$main.doInvoke(main.clj:421)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Subprocess failed
```

`lein -v` says,

`Leiningen 2.5.3 on Java 1.8.0_31 Java HotSpot(TM) 64-Bit Server VM`

**Comment by metasoarous** [comment]
Thanks for the bug report!

Huh; Thought I had fixed this. I guess not. Problem is that I switched from a local lein-git-deps of an older version of datsync to an updated version of datsync (on clojars) with some changed namespaces. I think when I tested it must have been using a stale datsync target. All you should have to do is switch over every instance of `datsync.client.core` to `datsync.client` in the client namespace declarations. That _should_ solve the problem.

I can try to fix this in a couple of days, but I would greatly appreciate a PR if you have the time :-)

**Comment by metasoarous** [comment]
@elsehow Actually, have some time to work on this today. Looks like it's a little more than the namespaces; there was some other code that wasn't building properly as well... I'll fix that and push shortly...

**Comment by elsehow** [comment]
@metasoarous cool!!

**Comment by metasoarous** [comment]
@elsehow OK; This should be fixed now! Let me know if you have any issues getting things to run. And keep in mind that I'm doing a complete rewrite of the datview code (currently under the nouveau ns), so if you're interested in that don't judge too hastily :-)

**Comment by elsehow** [comment]
@metasoarous awesome! works now.

I am not a judgemental sort of person! I think this project is really cool conceptually, and I'm interested to see how it evolves.

BTW, the data structure I mentioned to you at clojure/west is [hyperlog](https://github.com/mafintosh/hyperlog). Some relevant hacks include [swarmlog](https://github.com/substack/swarmlog) and [hyperreal](https://github.com/elsehow/hyperreal).

**Comment by metasoarous** [comment]
Ah! Gotit! Didn't recognize your name at first, but I remember meeting and chatting now. Thanks for checking catalysis out! And doubly thanks for the links! I'll check those out.

Cheers

**Comment by elsehow** [comment]
let me know what you think! I'm building a decentralized MUD as my hobby project at the moment, will keep you updated / check back with catalysis now and again (watching the project now)
