### ISSUE TITLE
First run: "Error in component :remote in system function"

### ISSUE THREAD

**Issue by theronic** [metasoarous/catalysis#33]
Cloned datsys, typed `lein repl` and then eval'd `(run)`. Everything builds, but when I try to connect browser, I get this in inspector console and a blank browser window:

```
"TypeError: Cannot read property 'call' of undefined
    at dat.remote.impl.sente.SenteRemote.com$stuartsierra$component$Lifecycle$start$arity$1 (http://localhost:2358/js/compiled/out/dat/remote/impl/sente.js:463:61)
    at com$stuartsierra$component$start (http://localhost:2358/js/compiled/out/com/stuartsierra/component.js:19:18)
    at cljs.core.Var.G__8696__2 (http://localhost:2358/js/compiled/out/cljs/core.js:3705:120)
    at cljs.core.Var.G__8696 [as call] (http://localhost:2358/js/compiled/out/cljs/core.js:3854:19)
    at cljs.core.Var.apply (http://localhost:2358/js/compiled/out/cljs/core.js:3927:24)
    at Function.cljs.core.apply.cljs$core$IFn$_invoke$arity$3 (http://localhost:2358/js/compiled/out/cljs/core.js:13027:10)
    at cljs$core$apply (http://localhost:2358/js/compiled/out/cljs/core.js:12984:24)
    at com$stuartsierra$component$try_action (http://localhost:2358/js/compiled/out/com/stuartsierra/component.js:155:28)
    at http://localhost:2358/js/compiled/out/com/stuartsierra/component.js:188:87
    at http://localhost:2358/js/compiled/out/cljs/core.js:4895:96"
```

![image](https://cloud.githubusercontent.com/assets/1011676/25057867/006ec98a-2174-11e7-8a28-fe0cac756250.png)

**Comment by theronic** [comment]
If I save a *.cljs file, Figwheel gets notified of a change, but my browser client screen is still blank

**Comment by metasoarous** [comment]
@theronic Just repeating here what we sorted out in chat; The master branch does not appear to have this issue, so anyone else seeing this should stick there for now. The dev branch is undergoing a major refactor, and once that's done the coast should be clear to work with dev. I think this particular issue should either be resolved now, or is just a result of not running on the latest dev checkouts from the other projects. Hopefully we'll get another release soon here.
